# Generated by Django 4.0 on 2022-03-25 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='just_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 20, 2, 27, 26384, tzinfo=utc)),
        ),
    ]
