# Generated by Django 4.0 on 2022-03-25 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_article_just_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='just_date',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 20, 4, 2, 260292, tzinfo=utc)),
        ),
    ]
