# Generated by Django 4.0 on 2022-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_remove_article_just_date_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
