# Generated by Django 4.0 on 2022-03-25 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 20, 9, 5, 113100, tzinfo=utc)),
        ),
    ]
